const EXH_HOST = import.meta.env.VITE_EXH_HOST
const EXH_CLIENT_ID = import.meta.env.VITE_EXH_CLIENT_ID
const EXH_CLIENT_SECRET = import.meta.env.VITE_EXH_CLIENT_SECRET
const EXH_CLIENT_USERNAME = import.meta.env.VITE_EXH_CLIENT_USERNAME
const EXH_CLIENT_PASSWORD = import.meta.env.VITE_EXH_CLIENT_PASSWORD

export default {
    EXH_HOST,
    EXH_CLIENT_ID,
    EXH_CLIENT_SECRET,
    EXH_CLIENT_USERNAME,
    EXH_CLIENT_PASSWORD,
}
